# Generated by Django 4.0.3 on 2022-03-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Image',
        ),
    ]
