# Generated by Django 3.2.9 on 2022-03-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_category_location_image_date_posted_image_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photo',
            new_name='image',
        ),
    ]
